version: '3.8'

services:
  back-end:
    build: ./back-end
    ports:
      - 4000:4000
    volumes:
      - ./back-end/src:/app/src
  web-app:
    build: ./web-app
    ports:
      - 3000:3000
    volumes:
      - ./web-app/src:/app/src